# Generated by Django 3.2.5 on 2021-07-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_order_uniqueid1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uniqueid2',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
