# Generated by Django 3.2.5 on 2021-07-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_order_uniqueid2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dim_coupon_coupon_id',
            field=models.PositiveIntegerField(help_text='Order coupon id', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dim_coupon_coupon_name',
            field=models.CharField(help_text='Order coupon name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fact_order_DestinationDetail',
            field=models.TextField(help_text='Order Destination detail', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fact_order_coupon_coupon_amount',
            field=models.PositiveIntegerField(help_text='Order coupon amount key', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fact_order_coupon_coupon_key',
            field=models.PositiveIntegerField(help_text='Order coupon key', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fact_order_coupon_coupon_quantity',
            field=models.PositiveIntegerField(help_text='Order coupon quantity key', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fact_order_coupon_date_added',
            field=models.DateTimeField(help_text='Order coupon date added', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fact_order_coupon_date_modified',
            field=models.DateTimeField(help_text='Order coupon date modified', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fact_order_coupon_order_attribute_key',
            field=models.PositiveBigIntegerField(help_text='Order coupon order attribute key', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fact_order_coupon_order_date_key',
            field=models.PositiveIntegerField(help_text='Order coupon order date key', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fact_order_coupon_order_id',
            field=models.PositiveIntegerField(help_text='Order coupon order id', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fact_order_coupon_order_time_key',
            field=models.PositiveIntegerField(help_text='Order coupon order time key', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='new_coupon_amount',
            field=models.PositiveIntegerField(help_text='Order coupon amount', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_id_cnt',
            field=models.PositiveIntegerField(help_text='Coupon id cnt', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='dim_unit_unit_id',
            field=models.PositiveIntegerField(help_text='Dim Unit unit id', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Coupon_Amount',
            field=models.DecimalField(decimal_places=4, help_text='Order coupon amount', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Date_Added',
            field=models.DateTimeField(help_text='Order date added', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Date_Modified',
            field=models.DateTimeField(help_text='Order date modified', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Discount_Amount',
            field=models.DecimalField(decimal_places=4, help_text='Order discount amount', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Donations',
            field=models.DecimalField(decimal_places=4, help_text='Order donations', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Employee_Key',
            field=models.IntegerField(help_text='Order employee key', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Giftcard_Sales',
            field=models.DecimalField(decimal_places=4, help_text='Order giftcard sales', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_HashValue',
            field=models.TextField(help_text='Order hash value', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Item_Count',
            field=models.PositiveSmallIntegerField(help_text='Order item count', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Net_Food_Sales',
            field=models.DecimalField(decimal_places=4, help_text='Order net food sales', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Net_Food_Sales1',
            field=models.DecimalField(decimal_places=4, help_text='Order net food sales 1', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Net_NonFood_Sales',
            field=models.DecimalField(decimal_places=4, help_text='Order unique id 1', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Order_Attribute_Key',
            field=models.PositiveSmallIntegerField(help_text='Order attribute key', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Order_Date_Key',
            field=models.PositiveIntegerField(help_text='Order order date key', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Order_ID',
            field=models.PositiveIntegerField(help_text='Order id', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Order_Time_Key',
            field=models.PositiveIntegerField(help_text='Order order time key', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Register_Key',
            field=models.PositiveSmallIntegerField(help_text='Order register key', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Tax_Collected',
            field=models.DecimalField(decimal_places=4, help_text='Order tax collected', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Taxable_Sales',
            field=models.DecimalField(decimal_places=4, help_text='Order taxable sales', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Total_Order_Amount',
            field=models.DecimalField(decimal_places=4, help_text='Order total order amount', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_Unit_Key',
            field=models.PositiveSmallIntegerField(help_text='Order unit key', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fact_order_order_key',
            field=models.PositiveIntegerField(help_text='Order key', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_enddate',
            field=models.PositiveIntegerField(help_text='End date', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_startdate',
            field=models.PositiveIntegerField(help_text='Start date', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='uniqueid1',
            field=models.CharField(help_text='Order unique id 1', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='uniqueid2',
            field=models.CharField(help_text='Order unique id 2', max_length=150, null=True),
        ),
    ]
