# Generated by Django 3.2.5 on 2021-07-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20210727_0719'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['dim_unit_unit_id', 'dim_coupon_coupon_id'], name='sales_order_dim_uni_5ced38_idx'),
        ),
    ]
