# Generated by Django 3.2.5 on 2021-07-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_rawcsvfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawcsvfile',
            old_name='filname',
            new_name='filename',
        ),
        migrations.AlterField(
            model_name='rawcsvfile',
            name='file',
            field=models.FileField(upload_to='raw_file/'),
        ),
    ]
