# Generated by Django 3.2.5 on 2021-07-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20210728_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawcsvfile',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'InProgress'), (2, 'Done')], default=0),
        ),
        migrations.AlterField(
            model_name='rawcsvfile',
            name='file',
            field=models.FileField(upload_to='csv/'),
        ),
    ]
